#!/usr/bin/env bun

/**
 * 🛡️ Webhook Payload Byte-Size Limiter & Receiver Guard — automation:integrations
 *
 * Capabilities:
 *   - Enforces early byte-ceiling defense (HTTP 413 Payload Too Large) against OOM/DoS
 *   - Upfront `Content-Length` pre-check + streaming byte counter for chunked transfers
 *   - Scaffolds hardened webhook receiver templates for Bun, Express, and Hono
 *   - Preserves raw buffer integrity for cryptographic HMAC signature verification
 *
 * Usage:
 *   bun automation/scripts/webhook-guard.ts [options]
 *
 * Examples:
 *   bun automation/scripts/webhook-guard.ts --scaffold bun --max-bytes 524288
 *   bun automation/scripts/webhook-guard.ts --test-file payload.json --max-bytes 1048576
 */

import { existsSync, statSync } from "node:fs";
import { resolve } from "node:path";
import { parseArgs } from "node:util";

export const DEFAULT_MAX_BYTES = 1024 * 1024; // 1MB

export interface PayloadCheckResult {
  allowed: boolean;
  size: number;
  limit: number;
  formattedSize: string;
  formattedLimit: string;
  error?: string;
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

export function validatePayloadSize(sizeInBytes: number, maxBytes: number = DEFAULT_MAX_BYTES): PayloadCheckResult {
  const allowed = sizeInBytes <= maxBytes;
  return {
    allowed,
    size: sizeInBytes,
    limit: maxBytes,
    formattedSize: formatBytes(sizeInBytes),
    formattedLimit: formatBytes(maxBytes),
    error: allowed
      ? undefined
      : `Payload size (${formatBytes(sizeInBytes)}) exceeds maximum allowed ceiling of ${formatBytes(maxBytes)}. Request must be rejected with HTTP 413 Payload Too Large.`,
  };
}

export function scaffoldWebhookHandler(
  runtime: "bun" | "express" | "hono" = "bun",
  maxBytes: number = DEFAULT_MAX_BYTES,
): string {
  switch (runtime) {
    case "bun":
      return `// Bun Native HTTP Server Webhook Receiver with Payload Byte-Size Limiter
// Auto-generated by automation:integrations webhook-guard

const MAX_BYTES = ${maxBytes}; // ${formatBytes(maxBytes)}

export default {
  port: 3000,
  async fetch(req: Request): Promise<Response> {
    const url = new URL(req.url);

    if (req.method === "POST" && url.pathname === "/webhooks/incoming") {
      // 1. Upfront Content-Length check
      const contentLengthHeader = req.headers.get("content-length");
      if (contentLengthHeader) {
        const contentLength = parseInt(contentLengthHeader, 10);
        if (contentLength > MAX_BYTES) {
          return new Response(
            JSON.stringify({ error: "Payload Too Large", limit: MAX_BYTES, received: contentLength }),
            { status: 413, headers: { "Content-Type": "application/json" } }
          );
        }
      }

      // 2. Streaming reader with byte counter for chunked/streaming payloads
      const reader = req.body?.getReader();
      if (!reader) {
        return new Response(JSON.stringify({ error: "Empty request body" }), { status: 400 });
      }

      const chunks: Uint8Array[] = [];
      let totalBytes = 0;

      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          if (value) {
            totalBytes += value.length;
            if (totalBytes > MAX_BYTES) {
              await reader.cancel("Payload ceiling exceeded");
              return new Response(
                JSON.stringify({ error: "Payload Too Large", limit: MAX_BYTES, bytesRead: totalBytes }),
                { status: 413, headers: { "Content-Type": "application/json" } }
              );
            }
            chunks.push(value);
          }
        }
      } catch (err) {
        return new Response(JSON.stringify({ error: "Stream aborted" }), { status: 400 });
      }

      // 3. Assemble raw body buffer for HMAC verification
      const rawBuffer = Buffer.concat(chunks);

      // Verify HMAC against rawBuffer here before JSON parsing...
      const payload = JSON.parse(rawBuffer.toString("utf8"));

      return new Response(JSON.stringify({ success: true, processedBytes: totalBytes }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }

    return new Response("Not Found", { status: 404 });
  },
};
`;

    case "express":
      return `// Express.js Webhook Receiver with Raw Buffer Byte-Size Guard
// Auto-generated by automation:integrations webhook-guard

import express, { Request, Response, NextFunction } from "express";

const app = express();
const MAX_BYTES = ${maxBytes}; // ${formatBytes(maxBytes)}

// Raw body parser with strict limit and buffer retention for HMAC verification
app.post(
  "/webhooks/incoming",
  express.raw({
    type: "application/json",
    limit: MAX_BYTES,
    verify: (req: any, _res: any, buf: Buffer) => {
      req.rawBody = buf;
    },
  }),
  (req: Request, res: Response) => {
    // req.rawBody contains raw Buffer for HMAC validation
    try {
      const payload = JSON.parse((req as any).rawBody.toString("utf8"));
      return res.status(200).json({ success: true });
    } catch (e) {
      return res.status(400).json({ error: "Malformed JSON payload" });
    }
  }
);

// Express Error Handler for HTTP 413
app.use((err: any, _req: Request, res: Response, next: NextFunction) => {
  if (err.type === "entity.too.large" || err.status === 413) {
    return res.status(413).json({ error: "Payload Too Large", limit: MAX_BYTES });
  }
  next(err);
});

app.listen(3000, () => console.log("Webhook listener on port 3000"));
`;

    case "hono":
      return `// Hono / Cloudflare Workers Webhook Receiver with Streaming Byte Ceiling
// Auto-generated by automation:integrations webhook-guard

import { Hono } from "hono";

const app = new Hono();
const MAX_BYTES = ${maxBytes}; // ${formatBytes(maxBytes)}

app.post("/webhooks/incoming", async (c) => {
  const contentLength = c.req.header("content-length");
  if (contentLength && parseInt(contentLength, 10) > MAX_BYTES) {
    return c.json({ error: "Payload Too Large", limit: MAX_BYTES }, 413);
  }

  const rawBuffer = await c.req.arrayBuffer();
  if (rawBuffer.byteLength > MAX_BYTES) {
    return c.json({ error: "Payload Too Large", limit: MAX_BYTES }, 413);
  }

  // Use rawBuffer for cryptographic HMAC verification before parsing
  const json = JSON.parse(new TextDecoder().decode(rawBuffer));
  return c.json({ success: true, bytes: rawBuffer.byteLength });
});

export default app;
`;
  }
}

if (import.meta.main) {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      scaffold: { type: "string" },
      "test-file": { type: "string" },
      "check-bytes": { type: "string" },
      "max-bytes": { type: "string" },
      json: { type: "boolean", default: false },
      help: { type: "boolean", short: "h", default: false },
    },
    allowPositionals: true,
  });

  if (values.help) {
    console.log(`
🛡️ webhook-guard.ts — Webhook Payload Byte-Size Limiter & Receiver Guard (automation)

Usage:
  bun webhook-guard.ts [options]

Commands:
  --scaffold <runtime>      Scaffold webhook receiver (bun, express, hono)
  --test-file <path>        Test a file size against maximum byte limit
  --check-bytes <bytes>     Validate numeric byte count against ceiling

Options:
  --max-bytes <bytes>       Ceiling threshold in bytes (default: 1048576 / 1MB)
  --json                    Output machine-readable JSON
  -h, --help                Show this help message
`);
    process.exit(0);
  }

  const maxBytes = values["max-bytes"] ? parseInt(values["max-bytes"], 10) : DEFAULT_MAX_BYTES;

  if (values.scaffold) {
    const runtime = (values.scaffold.toLowerCase() as "bun" | "express" | "hono") || "bun";
    const code = scaffoldWebhookHandler(runtime, maxBytes);
    if (values.json) {
      console.log(JSON.stringify({ runtime, maxBytes, code }, null, 2));
    } else {
      console.log(`\n🛡️ Webhook Receiver Template (${runtime.toUpperCase()} - Limit: ${formatBytes(maxBytes)}):`);
      console.log(code);
    }
    process.exit(0);
  }

  if (values["test-file"]) {
    const p = resolve(process.cwd(), values["test-file"]);
    if (!existsSync(p)) {
      console.error(`❌ File not found: ${p}`);
      process.exit(1);
    }
    const stat = statSync(p);
    const res = validatePayloadSize(stat.size, maxBytes);
    if (values.json) {
      console.log(JSON.stringify({ file: values["test-file"], ...res }, null, 2));
    } else {
      console.log(`\n📦 Webhook Payload Size Audit:`);
      console.log(`  File:   ${values["test-file"]}`);
      console.log(`  Size:   ${res.formattedSize} (${res.size} bytes)`);
      console.log(`  Limit:  ${res.formattedLimit} (${res.limit} bytes)`);
      console.log(`  Status: ${res.allowed ? "✅ ALLOWED" : "🚨 REJECTED (HTTP 413)"}`);
      if (res.error) console.log(`  Error:  ${res.error}`);
    }
    process.exit(res.allowed ? 0 : 1);
  }

  if (values["check-bytes"]) {
    const bytes = parseInt(values["check-bytes"], 10);
    const res = validatePayloadSize(bytes, maxBytes);
    if (values.json) {
      console.log(JSON.stringify(res, null, 2));
    } else {
      console.log(`\n📦 Byte Count Check:`);
      console.log(`  Size:   ${res.formattedSize}`);
      console.log(`  Limit:  ${res.formattedLimit}`);
      console.log(`  Status: ${res.allowed ? "✅ ALLOWED" : "🚨 REJECTED (HTTP 413)"}`);
    }
    process.exit(res.allowed ? 0 : 1);
  }

  console.log("No command passed. Pass --help for options.");
  process.exit(0);
}
