#!/usr/bin/env bun

/**
 * ⚡ Cloudflare OS Living Deliverables Engine — devops:cloudflare
 *
 * Provides:
 *   - Local `workerd` / Miniflare preview runtime container scaffolding
 *   - Ephemeral token-authenticated client review links via Quick Tunnels (`*.trycloudflare.com`)
 *   - Interactive client feedback banner & multi-viewport frame switcher overlay
 *   - Expiring access gate (default: 48h TTL) for secure agency-client previews
 *
 * Usage:
 *   bun devops/scripts/living-deliverable.ts [workspaceRoot] [options]
 *
 * Examples:
 *   bun devops/scripts/living-deliverable.ts --scaffold "client-acme-v1" --client "ACME" --target-port 3000
 *   bun devops/scripts/living-deliverable.ts --check-expiry "client-acme-v1"
 */

import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseArgs } from "node:util";

export interface DeliverableOptions {
  slug: string;
  client?: string;
  title?: string;
  targetPort?: number;
  targetDir?: string;
  expiresInHours?: number;
}

export interface DeliverableMetadata {
  slug: string;
  client: string;
  title: string;
  token: string;
  targetPort: number;
  targetDir: string;
  createdAt: string;
  expiresAt: string;
  expired: boolean;
}

export interface ScaffoldResult {
  success: boolean;
  deliverableDir: string;
  metadata: DeliverableMetadata;
  filesCreated: string[];
  reviewUrlPattern: string;
  error?: string;
}

export interface ExpiryCheckResult {
  slug: string;
  expired: boolean;
  expiresAt: string;
  hoursRemaining: number;
  client: string;
}

export function generateToken(): string {
  return randomBytes(16).toString("hex");
}

export function scaffoldLivingDeliverable(workspaceRoot: string, options: DeliverableOptions): ScaffoldResult {
  try {
    const slug = options.slug.replace(/[^a-zA-Z0-9_-]/g, "-").toLowerCase();
    const deliverableDir = resolve(workspaceRoot, ".agents", "deliverables", slug);

    if (!existsSync(deliverableDir)) {
      mkdirSync(deliverableDir, { recursive: true });
    }

    const token = generateToken();
    const client = options.client || "Confidential Client";
    const title = options.title || `Living Deliverable — ${slug}`;
    const targetPort = options.targetPort || 3000;
    const targetDir = options.targetDir || "dist";
    const expiresInHours = options.expiresInHours || 48;

    const createdAtDate = new Date();
    const expiresAtDate = new Date(createdAtDate.getTime() + expiresInHours * 60 * 60 * 1000);

    const metadata: DeliverableMetadata = {
      slug,
      client,
      title,
      token,
      targetPort,
      targetDir,
      createdAt: createdAtDate.toISOString(),
      expiresAt: expiresAtDate.toISOString(),
      expired: false,
    };

    const filesCreated: string[] = [];

    // 1. Write metadata.json
    const metaPath = resolve(deliverableDir, "metadata.json");
    writeFileSync(metaPath, JSON.stringify(metadata, null, 2), "utf8");
    filesCreated.push(metaPath);

    // 2. Write wrangler.jsonc with workerd runtime definition
    const wranglerConfig = {
      $schema: "./node_modules/wrangler/config-schema.json",
      name: `deliverable-${slug}`,
      main: "worker.ts",
      compatibility_date: "2026-09-01",
      compatibility_flags: ["nodejs_compat"],
      vars: {
        DELIVERABLE_SLUG: slug,
        CLIENT_CODENAME: client,
        EXPIRES_AT: expiresAtDate.toISOString(),
        REVIEW_TOKEN: token,
        UPSTREAM_PORT: targetPort.toString(),
      },
      assets: {
        directory: resolve(workspaceRoot, targetDir),
        binding: "ASSETS",
      },
    };
    const wranglerPath = resolve(deliverableDir, "wrangler.jsonc");
    writeFileSync(wranglerPath, JSON.stringify(wranglerConfig, null, 2), "utf8");
    filesCreated.push(wranglerPath);

    // 3. Write living deliverable worker wrapper
    const workerScript = `// Cloudflare OS Living Deliverable Worker Runtime
// Auto-generated by devops:cloudflare living-deliverable engine

export interface Env {
  DELIVERABLE_SLUG: string;
  CLIENT_CODENAME: string;
  EXPIRES_AT: string;
  REVIEW_TOKEN: string;
  UPSTREAM_PORT: string;
  ASSETS?: { fetch: (req: Request) => Promise<Response> };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // 1. Ephemeral Expiry Gate Check
    const expiryTime = new Date(env.EXPIRES_AT).getTime();
    if (Date.now() > expiryTime) {
      return new Response(
        \`<!DOCTYPE html>
<html>
<head><title>Preview Expired</title><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="font-family:system-ui,sans-serif;padding:3rem;text-align:center;background:#0d1117;color:#c9d1d9;">
  <h1 style="color:#f85149;">⏳ Client Review Window Expired</h1>
  <p>This living deliverable preview expired on <strong>\${env.EXPIRES_AT}</strong>.</p>
  <p>Please contact your agency delivery lead to request an extended review pass.</p>
</body>
</html>\`,
        { status: 410, headers: { "Content-Type": "text/html; charset=utf-8" } }
      );
    }

    // 2. Token Authentication Gate
    const reqToken = url.searchParams.get("review_token") || request.headers.get("x-review-token");
    if (reqToken !== env.REVIEW_TOKEN) {
      return new Response(
        \`<!DOCTYPE html>
<html>
<head><title>Unauthorized Preview</title><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="font-family:system-ui,sans-serif;padding:3rem;text-align:center;background:#0d1117;color:#c9d1d9;">
  <h1 style="color:#e3b341;">🔒 Protected Agency Deliverable</h1>
  <p>A valid <code>?review_token=</code> query parameter or header is required to access this preview.</p>
</body>
</html>\`,
        { status: 401, headers: { "Content-Type": "text/html; charset=utf-8" } }
      );
    }

    // 3. Handle Client Feedback Ingestion API
    if (url.pathname === "/__deliverable/feedback" && request.method === "POST") {
      try {
        const body = await request.json();
        return new Response(
          JSON.stringify({ success: true, receivedAt: new Date().toISOString(), body }),
          { status: 200, headers: { "Content-Type": "application/json" } }
        );
      } catch (e) {
        return new Response(JSON.stringify({ error: "Invalid JSON feedback" }), { status: 400 });
      }
    }

    // 4. Fetch upstream response from assets or local dev server
    let res: Response;
    if (env.ASSETS) {
      res = await env.ASSETS.fetch(request);
    } else {
      const upstreamUrl = \`http://localhost:\${env.UPSTREAM_PORT}\${url.pathname}\${url.search}\`;
      res = await fetch(upstreamUrl, {
        method: request.method,
        headers: request.headers,
        body: request.body,
      });
    }

    // 5. Inject Review Banner & Viewport Switcher for HTML documents
    const contentType = res.headers.get("content-type") || "";
    if (contentType.includes("text/html")) {
      const originalHtml = await res.text();
      const bannerHtml = \`
<!-- Agency Living Deliverable Review Overlay -->
<div id="__deliverable_bar" style="position:fixed;top:0;left:0;right:0;height:42px;background:#161b22;border-bottom:1px solid #30363d;color:#f0f6fc;display:flex;align-items:center;justify-content:space-between;padding:0 1rem;font-family:system-ui,sans-serif;font-size:13px;z-index:999999;">
  <div style="display:flex;align-items:center;gap:0.75rem;">
    <span style="background:#238636;color:#ffffff;padding:2px 8px;border-radius:12px;font-weight:600;font-size:11px;">LIVE REVIEW</span>
    <span><strong>\${env.CLIENT_CODENAME}</strong>: \${env.DELIVERABLE_SLUG}</span>
    <span style="color:#8b949e;font-size:11px;">(Expires: \${new Date(env.EXPIRES_AT).toLocaleDateString()})</span>
  </div>
  <div style="display:flex;align-items:center;gap:0.5rem;">
    <button onclick="document.body.style.maxWidth='390px';document.body.style.margin='50px auto 0 auto';" style="background:#21262d;color:#c9d1d9;border:1px solid #30363d;padding:3px 8px;border-radius:4px;cursor:pointer;font-size:11px;">📱 Mobile (390px)</button>
    <button onclick="document.body.style.maxWidth='820px';document.body.style.margin='50px auto 0 auto';" style="background:#21262d;color:#c9d1d9;border:1px solid #30363d;padding:3px 8px;border-radius:4px;cursor:pointer;font-size:11px;">📱 Tablet (820px)</button>
    <button onclick="document.body.style.maxWidth='100%';document.body.style.margin='42px 0 0 0';" style="background:#21262d;color:#c9d1d9;border:1px solid #30363d;padding:3px 8px;border-radius:4px;cursor:pointer;font-size:11px;">💻 Full (100%)</button>
  </div>
</div>
<style>body { margin-top: 42px !important; transition: max-width 0.2s ease; }</style>
\`;
      const injectedHtml = originalHtml.replace(/<body([^>]*)>/i, \`<body$1>\${bannerHtml}\`);
      return new Response(injectedHtml, {
        status: res.status,
        headers: res.headers,
      });
    }

    return res;
  }
};
`;
    const workerPath = resolve(deliverableDir, "worker.ts");
    writeFileSync(workerPath, workerScript, "utf8");
    filesCreated.push(workerPath);

    return {
      success: true,
      deliverableDir,
      metadata,
      filesCreated,
      reviewUrlPattern: `https://<tunnel-subdomain>.trycloudflare.com/?review_token=${token}`,
    };
  } catch (err: unknown) {
    return {
      success: false,
      deliverableDir: "",
      metadata: {
        slug: options.slug,
        client: options.client || "",
        title: options.title || "",
        token: "",
        targetPort: options.targetPort || 3000,
        targetDir: options.targetDir || "dist",
        createdAt: new Date().toISOString(),
        expiresAt: new Date().toISOString(),
        expired: true,
      },
      filesCreated: [],
      reviewUrlPattern: "",
      error: String(err),
    };
  }
}

export function checkDeliverableExpiry(workspaceRoot: string, slug: string): ExpiryCheckResult {
  const metaPath = resolve(workspaceRoot, ".agents", "deliverables", slug, "metadata.json");
  if (!existsSync(metaPath)) {
    throw new Error(`Deliverable metadata not found: ${metaPath}`);
  }

  const data = JSON.parse(readFileSync(metaPath, "utf8")) as DeliverableMetadata;
  const now = Date.now();
  const expiryTime = new Date(data.expiresAt).getTime();
  const expired = now > expiryTime;
  const hoursRemaining = Math.max(0, Math.round((expiryTime - now) / (1000 * 60 * 60)));

  return {
    slug: data.slug,
    expired,
    expiresAt: data.expiresAt,
    hoursRemaining,
    client: data.client,
  };
}

if (import.meta.main) {
  const { values, positionals } = parseArgs({
    args: process.argv.slice(2),
    options: {
      scaffold: { type: "string" },
      client: { type: "string" },
      title: { type: "string" },
      "target-port": { type: "string" },
      "target-dir": { type: "string" },
      "expires-in": { type: "string" },
      "check-expiry": { type: "string" },
      json: { type: "boolean", default: false },
      help: { type: "boolean", short: "h", default: false },
    },
    allowPositionals: true,
  });

  const workspaceRoot = positionals[0] ? resolve(process.cwd(), positionals[0]) : process.cwd();

  if (values.help) {
    console.log(`
⚡ living-deliverable.ts — Cloudflare OS Living Deliverables Engine (devops:cloudflare)

Usage:
  bun living-deliverable.ts [workspaceRoot] [options]

Core Commands:
  --scaffold <slug>      Scaffold workerd preview container & review harness in .agents/deliverables/<slug>
  --check-expiry <slug>  Verify if an ephemeral client review deliverable has expired

Options:
  --client <name>        Client codename (NDA protected, e.g. "ACME")
  --title <title>        Human-readable title for the deliverable
  --target-port <port>   Local development port to proxy (default: 3000)
  --target-dir <dir>     Static build output directory (default: dist)
  --expires-in <hours>   Lifetime of ephemeral review token in hours (default: 48)
  --json                 Output machine-readable JSON
  -h, --help             Show this help message
`);
    process.exit(0);
  }

  if (values.scaffold) {
    const slug = values.scaffold;
    const targetPort = values["target-port"] ? parseInt(values["target-port"], 10) : 3000;
    const expiresInHours = values["expires-in"] ? parseInt(values["expires-in"], 10) : 48;

    const res = scaffoldLivingDeliverable(workspaceRoot, {
      slug,
      client: values.client,
      title: values.title,
      targetPort,
      targetDir: values["target-dir"] || "dist",
      expiresInHours,
    });

    if (values.json) {
      console.log(JSON.stringify(res, null, 2));
    } else {
      if (!res.success) {
        console.error(`\n❌ Failed to scaffold deliverable: ${res.error}`);
        process.exit(1);
      }
      console.log(`\n⚡ Living Deliverable Scaffolding Created:`);
      console.log(`  Directory:      ${res.deliverableDir}`);
      console.log(`  Client:         ${res.metadata.client}`);
      console.log(`  Expires At:     ${res.metadata.expiresAt}`);
      console.log(`  Review Token:   ${res.metadata.token}`);
      console.log(`  URL Pattern:    ${res.reviewUrlPattern}`);
      console.log(`  Files:`);
      for (const f of res.filesCreated) {
        console.log(`    - ${f}`);
      }
    }
    process.exit(res.success ? 0 : 1);
  }

  if (values["check-expiry"]) {
    try {
      const res = checkDeliverableExpiry(workspaceRoot, values["check-expiry"]);
      if (values.json) {
        console.log(JSON.stringify(res, null, 2));
      } else {
        console.log(`\n⏳ Living Deliverable Expiry Check:`);
        console.log(`  Deliverable:     ${res.slug} (${res.client})`);
        console.log(`  Status:          ${res.expired ? "🚨 EXPIRED" : "🟢 ACTIVE"}`);
        console.log(`  Expires At:      ${res.expiresAt}`);
        console.log(`  Hours Remaining: ${res.hoursRemaining}h`);
      }
      process.exit(res.expired ? 1 : 0);
    } catch (err: unknown) {
      console.error(`\n❌ Expiry check failed: ${String(err)}`);
      process.exit(1);
    }
  }

  console.log("No command specified. Use --scaffold <slug> or --check-expiry <slug>. Pass --help for options.");
  process.exit(0);
}
